# This does not run all targets, but builds all configured environments.
build:
	pio run

upload:
	pio run --target upload

clean:
	pio run --target clean

update:
	pio pkg update

# list all targets: pio run --list-targets

# vim: set noexpandtab:
